// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqqdN4CPV4vOdmzh6Rb80y7q2YM4M9Ol0',
    appId: '1:1056301880946:web:910c4e764256eb953494eb',
    messagingSenderId: '1056301880946',
    projectId: 'flutter-15-57fbf',
    authDomain: 'flutter-15-57fbf.firebaseapp.com',
    storageBucket: 'flutter-15-57fbf.appspot.com',
    measurementId: 'G-JPMJ4MH282',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv7HXFcedSK_3zc61YhC3Tg3Bj1Wu1J5s',
    appId: '1:1056301880946:android:ebfe7f7d49887a443494eb',
    messagingSenderId: '1056301880946',
    projectId: 'flutter-15-57fbf',
    storageBucket: 'flutter-15-57fbf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3POCDqqATt1pD8MWgE33cssSjBM9U6Uc',
    appId: '1:1056301880946:ios:86fc3d9d1d2604663494eb',
    messagingSenderId: '1056301880946',
    projectId: 'flutter-15-57fbf',
    storageBucket: 'flutter-15-57fbf.appspot.com',
    iosBundleId: 'com.example.flutterClass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3POCDqqATt1pD8MWgE33cssSjBM9U6Uc',
    appId: '1:1056301880946:ios:6ba6b8d2287bbf183494eb',
    messagingSenderId: '1056301880946',
    projectId: 'flutter-15-57fbf',
    storageBucket: 'flutter-15-57fbf.appspot.com',
    iosBundleId: 'com.example.flutterClass.RunnerTests',
  );
}
